<?php

namespace App\Services\LegacyImport;

use App\Models\Organization;
use App\Models\User;
use App\Services\Audit\AuditLogger;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use JsonException;
use ZipArchive;

class LegacyImportService
{
    private const MAX_BYTES = 1073741824;

    public function __construct(private LegacyImportSchema $schema) {}

    public function upload(User $actor, UploadedFile $file): object
    {
        $zip = new ZipArchive;
        if ($zip->open($file->getRealPath()) !== true) {
            $this->schema->invalid('Choose a ZIP package generated by Export-LegacyHistory.ps1.');
        }
        $path = 'legacy-imports/'.$actor->organization_id.'/'.Str::uuid().'.jsonl';
        $disk = Storage::disk('local_private');
        try {
            $stat = $zip->statIndex(0);
            if ($zip->numFiles !== 1 || ! $stat || $stat['name'] !== 'history.jsonl' || $stat['size'] > self::MAX_BYTES) {
                $this->schema->invalid('The package must contain only history.jsonl, at most 1 GiB uncompressed.');
            }
            $input = $zip->getStream('history.jsonl');
            if ($input === false) {
                $this->schema->invalid('The package could not be read.');
            }
            $disk->makeDirectory(dirname($path));
            $output = fopen($disk->path($path), 'xb');
            try {
                $copied = stream_copy_to_stream($input, $output, self::MAX_BYTES + 1);
                if ($copied !== $stat['size']) {
                    $this->schema->invalid('The package size is invalid or the file is incomplete.');
                }
            } finally {
                fclose($input);
                fclose($output);
            }

            return $this->stagePrivateFile($actor, $path);
        } catch (\Throwable $exception) {
            $disk->delete($path);
            throw $exception;
        } finally {
            $zip->close();
        }
    }

    public function stagePrivateFile(User $actor, string $path): object
    {
        $disk = Storage::disk('local_private');
        if (! str_starts_with($path, 'legacy-imports/'.$actor->organization_id.'/') || str_contains($path, '..') || $disk->size($path) > self::MAX_BYTES) {
            $this->schema->invalid('Invalid private import file.');
        }
        $hash = hash_file('sha256', $disk->path($path));
        $stream = fopen($disk->path($path), 'rb');
        try {
            $manifest = $this->decodeLine($stream);
            $offset = ftell($stream);
        } finally {
            fclose($stream);
        }
        $this->validateManifest($manifest);
        $batch = DB::transaction(function () use ($actor, $manifest, $offset, $hash, $path): object {
            Organization::whereKey($actor->organization_id)->lockForUpdate()->firstOrFail();
            $existing = DB::table('legacy_import_batches')->where('organization_id', $actor->organization_id)->where('package_hash', $hash)->first();
            if ($existing) {
                return $existing;
            }
            $id = DB::table('legacy_import_batches')->insertGetId([
                'organization_id' => $actor->organization_id, 'created_by_user_id' => $actor->id,
                'source_key' => $manifest['source_key'], 'package_hash' => $hash, 'status' => 'STAGING',
                'private_path' => $path, 'byte_offset' => $offset, 'processed_rows' => 0,
                'expected_rows' => array_sum($manifest['counts']), 'manifest' => json_encode($manifest, JSON_THROW_ON_ERROR),
                'created_at' => now(), 'updated_at' => now(),
            ]);
            AuditLogger::log('legacy_import.staged', newValues: ['batch_id' => $id, 'package_hash' => $hash], actor: $actor);

            return $this->batch($actor, $id);
        });
        if ($batch->private_path !== $path) {
            $disk->delete($path);
        }

        return $batch;
    }

    public function batch(User $actor, int $id): object
    {
        $batch = DB::table('legacy_import_batches')->where('organization_id', $actor->organization_id)->where('id', $id)->first();
        abort_unless($batch, 404);

        return $batch;
    }

    public function advance(User $actor, int $id): object
    {
        try {
            return DB::transaction(function () use ($actor, $id): object {
                $batch = DB::table('legacy_import_batches')->where('organization_id', $actor->organization_id)->where('id', $id)->lockForUpdate()->first();
                abort_unless($batch, 404);
                if ($batch->status !== 'STAGING') {
                    return $batch;
                }
                $stream = fopen(Storage::disk('local_private')->path($batch->private_path), 'rb');
                try {
                    if (fseek($stream, $batch->byte_offset) !== 0) {
                        $this->schema->invalid('The import checkpoint could not be read.');
                    }
                    $rows = [];
                    for ($i = 0; $i < 500; $i++) {
                        if (ftell($stream) - $batch->byte_offset >= 4194304) {
                            break;
                        }
                        $data = $this->decodeLine($stream);
                        if ($data === null) {
                            break;
                        }
                        $record = $this->schema->record($data);
                        $identity = $record['source_table'].':'.$record['source_id'];
                        if (isset($rows[$identity])) {
                            $this->schema->invalid('The package repeats a source row identity.');
                        }
                        $rows[$identity] = [
                            ...array_fill_keys(['gross_amount', 'ppa_amount', 'discount_amount', 'net_amount', 'tax_amount', 'due_amount', 'charge_amount'], null),
                            ...$record, 'batch_id' => $id, 'organization_id' => $actor->organization_id,
                            'source_key' => $batch->source_key, 'created_at' => now(),
                        ];
                    }
                    if ($rows) {
                        $inserted = DB::table('legacy_import_records')->insertOrIgnore(array_values($rows));
                        if ($inserted !== count($rows)) {
                            $this->schema->invalid('The package repeats a source row identity.');
                        }
                    }
                    $processed = $batch->processed_rows + count($rows);
                    if ($processed > $batch->expected_rows) {
                        $this->schema->invalid('The package contains more rows than its manifest.');
                    }
                    DB::table('legacy_import_batches')->where('id', $id)->update([
                        'byte_offset' => ftell($stream), 'processed_rows' => $processed, 'updated_at' => now(),
                    ]);
                    if (feof($stream)) {
                        $counts = DB::table('legacy_import_records')->where('batch_id', $id)->selectRaw('source_table, COUNT(*) AS total')->groupBy('source_table')->pluck('total', 'source_table')->all();
                        $manifest = json_decode($batch->manifest, true, 32, JSON_THROW_ON_ERROR);
                        foreach ($manifest['counts'] as $table => $expected) {
                            if ((int) ($counts[$table] ?? 0) !== $expected) {
                                $this->schema->invalid('The package row counts do not match its manifest.');
                            }
                        }
                        $this->reconcile($id);
                        DB::table('legacy_import_batches')->where('id', $id)->update(['status' => 'READY', 'summary' => json_encode($this->summary($id), JSON_THROW_ON_ERROR)]);
                        AuditLogger::log('legacy_import.preview_ready', newValues: ['batch_id' => $id], actor: $actor);
                    }
                } finally {
                    fclose($stream);
                }

                return $this->batch($actor, $id);
            });
        } catch (ValidationException $exception) {
            DB::table('legacy_import_batches')->where('organization_id', $actor->organization_id)->where('id', $id)->where('status', 'STAGING')->update([
                'status' => 'FAILED', 'error_message' => $exception->errors()['package'][0] ?? 'Invalid import package.', 'updated_at' => now(),
            ]);
            throw $exception;
        }
    }

    public function finalize(User $actor, int $id, string $hash, string $reason): object
    {
        return DB::transaction(function () use ($actor, $id, $hash, $reason): object {
            Organization::whereKey($actor->organization_id)->lockForUpdate()->firstOrFail();
            $batch = DB::table('legacy_import_batches')->where('organization_id', $actor->organization_id)->where('id', $id)->lockForUpdate()->first();
            abort_unless($batch, 404);
            if (! hash_equals($batch->package_hash, $hash)) {
                $this->schema->invalid('The preview no longer matches this import. Refresh it before continuing.');
            }
            if ($batch->status === 'IMPORTED') {
                return $batch;
            }
            if ($batch->status !== 'READY') {
                $this->schema->invalid('Finish the preview before importing history.');
            }
            DB::update("UPDATE legacy_import_records r SET disposition = CASE WHEN r.row_hash = old.row_hash THEN 'DUPLICATE' ELSE 'CONFLICT' END
                FROM legacy_import_records old WHERE r.batch_id = ? AND old.disposition = 'IMPORTED'
                AND old.organization_id = r.organization_id AND old.source_key = r.source_key
                AND old.source_table = r.source_table AND old.source_id = r.source_id", [$id]);
            DB::table('legacy_import_records')->where('batch_id', $id)->where('disposition', 'STAGED')->update(['disposition' => 'IMPORTED']);
            $summary = $this->summary($id);
            DB::table('legacy_import_batches')->where('id', $id)->update([
                'status' => 'IMPORTED', 'summary' => json_encode($summary, JSON_THROW_ON_ERROR),
                'finalized_at' => now(), 'finalized_by_user_id' => $actor->id, 'reason' => $reason, 'updated_at' => now(),
            ]);
            AuditLogger::log('legacy_import.finalized', newValues: ['batch_id' => $id, 'summary' => $summary, 'reason' => $reason], actor: $actor);

            return $this->batch($actor, $id);
        });
    }

    private function summary(int $id): array
    {
        return [
            'tables' => DB::table('legacy_import_records')->where('batch_id', $id)->selectRaw("source_table, COUNT(*) AS rows, SUM(CASE WHEN issues <> '[]'::jsonb THEN 1 ELSE 0 END) AS review_rows, SUM(due_amount)::text AS stored_amount_sum")->groupBy('source_table')->orderBy('source_table')->get()->all(),
            'dispositions' => DB::table('legacy_import_records')->where('batch_id', $id)->selectRaw('disposition, COUNT(*) AS total')->groupBy('disposition')->pluck('total', 'disposition')->all(),
        ];
    }

    private function reconcile(int $id): void
    {
        DB::update("UPDATE legacy_import_records r SET issues = issues || '[\"DUPLICATE_REFERENCE\"]'::jsonb
            WHERE batch_id = ? AND source_table IN ('tbl_bill_trans','tbl_or_trans','tbl_account','tbl_tarrif')
            AND EXISTS (SELECT 1 FROM legacy_import_records other WHERE other.batch_id = r.batch_id AND other.source_table = r.source_table AND other.reference = r.reference AND other.id <> r.id)", [$id]);
        foreach ([
            ['tbl_item_trans', 'reference', 'tbl_bill_trans', 'MISSING_BILL'],
            ['tbl_orbill_trans', 'reference', 'tbl_or_trans', 'MISSING_RECEIPT'],
            ['tbl_orbill_trans', 'related_reference', 'tbl_bill_trans', 'MISSING_BILL'],
            ['tbl_bill_trans', 'account_number', 'tbl_account', 'MISSING_ACCOUNT'],
            ['tbl_or_trans', 'account_number', 'tbl_account', 'MISSING_ACCOUNT'],
        ] as [$table, $column, $parent, $issue]) {
            DB::update("UPDATE legacy_import_records r SET issues = issues || ?::jsonb WHERE batch_id = ? AND source_table = ?
                AND NOT EXISTS (SELECT 1 FROM legacy_import_records p WHERE p.batch_id = r.batch_id AND p.source_table = ? AND p.reference = r.{$column})", [json_encode([$issue]), $id, $table, $parent]);
        }
        DB::update("UPDATE legacy_import_records SET issues = issues || '[\"MISSING_REFERENCE\"]'::jsonb WHERE batch_id = ? AND (reference IS NULL OR reference = '')", [$id]);
        foreach ([['tbl_bill_no', 'tbl_bill_trans'], ['tbl_or_no', 'tbl_or_trans']] as [$pool, $document]) {
            DB::update("UPDATE legacy_import_records r SET issues = issues || '[\"NUMBER_ALREADY_ISSUED\"]'::jsonb WHERE batch_id = ? AND source_table = ?
                AND EXISTS (SELECT 1 FROM legacy_import_records p WHERE p.batch_id = r.batch_id AND p.source_table = ? AND p.reference = r.reference)", [$id, $pool, $document]);
        }
        foreach ([['tbl_bill_trans', 'tbl_item_trans', ['gross', 'ppa', 'discount', 'net', 'tax', 'due']], ['tbl_or_trans', 'tbl_orbill_trans', ['gross', 'discount', 'net', 'tax']]] as [$header, $detail, $fields]) {
            $sums = implode(', ', array_map(fn ($field) => "SUM({$field}_amount) AS {$field}_amount", $fields));
            $parts = implode(', ', array_map(fn ($field) => "'{$field}_amount', jsonb_build_object('header',r.{$field}_amount::text,'lines',s.{$field}_amount::text,'difference',(r.{$field}_amount-s.{$field}_amount)::text)", $fields));
            $different = implode(' OR ', array_map(fn ($field) => "r.{$field}_amount IS DISTINCT FROM s.{$field}_amount", $fields));
            DB::update("WITH s AS (SELECT reference, COUNT(*) AS lines, {$sums} FROM legacy_import_records WHERE batch_id = ? AND source_table = ? GROUP BY reference)
                UPDATE legacy_import_records r SET reconciliation = jsonb_build_object('line_count',s.lines,'amounts',jsonb_build_object({$parts})),
                issues = CASE WHEN {$different} THEN issues || '[\"HEADER_DETAIL_DIFFERENCE\"]'::jsonb ELSE issues END
                FROM s WHERE r.batch_id = ? AND r.source_table = ? AND r.reference = s.reference", [$id, $detail, $id, $header]);
            DB::update("UPDATE legacy_import_records SET issues = issues || '[\"MISSING_DETAILS\"]'::jsonb WHERE batch_id = ? AND source_table = ? AND reconciliation IS NULL", [$id, $header]);
        }
        DB::update("UPDATE legacy_import_records SET issues = issues || '[\"LINE_ARITHMETIC_DIFFERENCE\"]'::jsonb
            WHERE batch_id = ? AND source_table = 'tbl_item_trans'
            AND (net_amount <> gross_amount-ppa_amount-discount_amount OR due_amount <> net_amount+tax_amount OR charge_amount <> gross_amount+tax_amount)", [$id]);
    }

    private function validateManifest(?array $manifest): void
    {
        $keys = ['format', 'version', 'source_key', 'exported_at', 'consistency', 'scope', 'counts'];
        if (! $manifest || array_diff(array_keys($manifest), $keys) || array_diff($keys, array_keys($manifest))
            || $manifest['format'] !== 'scipsi-legacy-history' || $manifest['version'] !== 1
            || ! is_string($manifest['source_key']) || ! preg_match('/^[a-zA-Z0-9][a-zA-Z0-9_-]{2,63}$/D', $manifest['source_key'])
            || ! in_array($manifest['consistency'], ['READ_ONLY_DATABASE', 'SNAPSHOT', 'RESTORED_SERIALIZABLE'], true)
            || ! in_array($manifest['scope'], ['FULL_HISTORY', 'SAMPLE'], true)
            || ! is_string($manifest['exported_at']) || ! preg_match('/^\d{4}-\d{2}-\d{2}T[0-9:.]+Z$/D', $manifest['exported_at'])
            || ! is_array($manifest['counts']) || array_diff(array_keys($manifest['counts']), array_keys($this->schema->tables()))
            || array_diff(array_keys($this->schema->tables()), array_keys($manifest['counts']))) {
            $this->schema->invalid('Invalid package manifest. Regenerate the package using the legacy exporter.');
        }
        foreach ($manifest['counts'] as $count) {
            if (! is_int($count) || $count < 0 || $count > 5000000) {
                $this->schema->invalid('Invalid table row count in the package.');
            }
        }
        if (array_sum($manifest['counts']) > 5000000) {
            $this->schema->invalid('The package exceeds the five-million-row limit.');
        }
    }

    /** @param resource $stream */
    private function decodeLine($stream): ?array
    {
        $line = fgets($stream, 1048577);
        if ($line === false) {
            return null;
        }
        if (strlen($line) >= 1048576) {
            $this->schema->invalid('A package row exceeds the one-megabyte limit.');
        }
        try {
            $data = json_decode($line, true, 32, JSON_THROW_ON_ERROR);
        } catch (JsonException) {
            $this->schema->invalid('The package contains invalid JSON.');
        }
        if (! is_array($data)) {
            $this->schema->invalid('Each package line must be a JSON object.');
        }

        return $data;
    }
}
